## Numpy


Numpy is a fundamental library for scientific computing in python

In [1]:
## for using numpy first we have to import it

import numpy as np

## Creating 1D array using numpy

arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
## lets try 2d array
from numpy import shape
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(shape(arr2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
from numpy import reshape
arr1.reshape(2,2) ## we can reshape the earlier declared array into different shape

array([[1, 2],
       [3, 4]])

In [19]:
np.arange(0,12,2).reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [20]:
## Identity Matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
import numpy as np
arr = np.array([1,2,3,4,5])

## Mean of the above array
avg = np.mean(arr)
print(avg)

## Standard Deviation of the array
std_dev = np.std(arr)
print(std_dev)

## Normalisation of the array --> it means that changing the mean of the array to '0' and std to 1
nrml = (arr - avg)/std_dev
print(nrml)

print(np.mean(nrml))
print(np.std(nrml))

3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


e

In [3]:
import numpy as np

ar = np.array([[1,2],[3,4]])
print(ar)

[[1 2]
 [3 4]]


In [ ]:
## Transpose of a matrix
ar.T

array([[1, 3],
       [2, 4]])

In [ ]:
## Determinent of a matrix
np.linalg.det(ar)

np.float64(-2.0000000000000004)

In [ ]:
### Rank of a matrix
np.linalg.matrix_rank(ar)

np.int64(2)